// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyDmBn3f6_GyWFutdxBE6bvVMC3A6uwL0S4',
//     appId: '1:760466312731:android:c83beddb60cba2594d72be',
//     messagingSenderId: '760466312731',
//     projectId: 'vas-reporting',
//     storageBucket: 'vas-reporting.firebasestorage.app',
//   );

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyDbvMENkRWsiJl5cBDUGT5l64jU_2vV2Fg',
//     appId: '1:760466312731:web:c104020aebd638464d72be',
//     messagingSenderId: '760466312731',
//     projectId: 'vas-reporting',
//     authDomain: 'vas-reporting.firebaseapp.com',
//     storageBucket: 'vas-reporting.firebasestorage.app',
//     measurementId: 'G-LFEW9K9BTY',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyBUDTVXm_VEEd7JHp50bh4P5vam3SR6zCk',
//     appId: '1:760466312731:ios:4f00ed2205f14a784d72be',
//     messagingSenderId: '760466312731',
//     projectId: 'vas-reporting',
//     storageBucket: 'vas-reporting.firebasestorage.app',
//     iosBundleId: 'com.example.vasReporting',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyBUDTVXm_VEEd7JHp50bh4P5vam3SR6zCk',
//     appId: '1:760466312731:ios:4f00ed2205f14a784d72be',
//     messagingSenderId: '760466312731',
//     projectId: 'vas-reporting',
//     storageBucket: 'vas-reporting.firebasestorage.app',
//     iosBundleId: 'com.example.vasReporting',
//   );

//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyDbvMENkRWsiJl5cBDUGT5l64jU_2vV2Fg',
//     appId: '1:760466312731:web:9054e07169874a564d72be',
//     messagingSenderId: '760466312731',
//     projectId: 'vas-reporting',
//     authDomain: 'vas-reporting.firebaseapp.com',
//     storageBucket: 'vas-reporting.firebasestorage.app',
//     measurementId: 'G-SXDR25MSMY',
//   );

// }